name: CI/CD Demo

on:
  push:
    branches:
      - 'gh-pages'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build style sheet
        run: npm run build

